source: .
branch: True
ignore:
  - */tests/*
  - */management/*
  - */migrations/*
  - venv/*
  - conveyances/wsgi.py
  - conveyances/asgi.py
  - manage.py

codecov:
  token: a34561f2-8d9f-4498-81c8-b9db7b944dfd
