# Generated by Django 4.0.3 on 2022-06-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0002_conveyancematter_comment_conveyancematter_complete_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matter",
            name="stages",
            field=models.JSONField(),
        ),
    ]
