# Generated by Django 4.0.3 on 2022-06-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matters", "0008_alter_bank_uuid_alter_conveyancematter_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matter",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
